# CSE110 Lab Assignment 6
This assignment is to guide you to solve everything you have learned so far by implementing functions in Python. 



Write your name, student id and CSE110 section below:

In [ ]:
#STUDENT NAME: Rowshon Ara Chowdhury
#STUDENT ID: 21201702
#CSE110 SECTION: 25

**<font color='red'>[MUST MAINTAIN VARIABLE NAMING CONVENTIONS FOR ALL THE TASKS]</font>**

## Write the Python code of the following problems:

### Task 1
Write a function called **even_checker** that takes a number as an argument and prints whether the number is even or odd **inside the function**.

===================================

**Example1:** \
**Function Call:**\
even_checker(5)\
**Output:**\
Odd!!

=============================

**Example2:** \
**Function Call:**\
even_checker(2)\
**Output:**\
Even!!

In [ ]:
# to do
def even_checker(num):
  if num%2==0:
    print("Even!!")
  else:
    print("Odd!!")
even_checker(2)

Even!!

### Task 2
Write a python function that takes the limit as an argument of the Fibonacci series and prints till that limit. 

===================================

**Function Call:**\
fibonacci(10)\
**Output:**\
0 1 1 2 3 5 8\
======================\
**Function Call:**\
fibonacci(5)\
**Output:**\
0 1 1 2 3 5

In [ ]:
# to do
def fibonacci(limit):
  a=0
  b=1
  print(a,b, end=" ")
  for i in range(1,limit+1):                 
    c=a+b
    a=b
    b=c
    if c<=limit:
     print(c,end=" ")
fibonacci(10)

0 1 1 2 3 5 8

### Task 3
Write a function called **foo_moo** that takes a number as an argument and **returns** the following statements according the below mentioned conditions. Then, finally prints the statement in the function call. 

* 	If the number is divisible by 2, it should return "Foo".
*   If the number is divisible by 3, it should return "Moo". 
*   If the number is divisible by both 2 and 3, it should return "FooMoo".
*   Otherwise, it returns "Boo".

===================================

**Example1:** \
**Function Call:**\
foo_moo(5)\
**Output:**\
Boo

=================


**Example2:** \
**Function Call:**\
foo_moo(4)\
**Output:**\
Foo

=================


**Example3:** \
**Function Call:**\
foo_moo(6)\
**Output:**\
FooMoo

In [ ]:
# to do
def foo_moo(num):
  if num%2==0 and num%3==0:
    return("FooMoo")
  elif num%3==0:
    return("Moo")
  elif num%2==0:
    return("Foo")
  else:
     return("Boo")
print(foo_moo(5))

Boo

### Task 4
Write a python function that takes a string as an argument. Your task is to calculate the number of uppercase letters and lowercase letters and print them in the function. 

===================================

**Function Call:**\
function_name('The quick Sand Man')\
**Output:**\
No. of Uppercase characters : 3\
No. of Lowercase Characters: 12\
============================\
**Function Call:**\
function_name('HaRRy PotteR')\
**Output:**\
No. of Uppercase characters : 5\
No. of Lowercase Characters: 6

In [ ]:
# to do
def function_name(name):
  count=0
  count1=0
  for i in name:
    if i!=' ':
      if i.isupper():
        count+=1
      else:
        count1+=1
  print(f'No. of Uppercase character: {count}')
  print(f'No. of Lowercase character: {count1}')
function_name('HaRRy PotteR')

No. of Uppercase character: 5
No. of Lowercase character: 6

### Task 5
Write a function called **calculate_tax** that takes 3 arguments: your age, salary, and current job designation.


Your first task is to take these arguments as user input and pass these values to the function.

Your second task is to implement the function and calculate the tax as the following conditions:
*  **NO TAX IF YOU ARE LESS THAN 18 YEARS OLD.**
*  **NO TAX IF YOU ARE THE PRESIDENT OF THE COMPANY** 
*  No tax if you get paid less than 10,000
*  5% tax if you get paid between 10K and 20K
*  10% tax if you get paid more than 20K


Finally return this tax value. Then print the returned value in the function call.

===================================

**Hints:**\
Here the job designation is a string, so it can be written in both uppercase and lower cases. So, you need to check the value ignoring the case.

===================================

**Example1:** \
**Input:**\
16\
20000\
Student\
**Function Call:**\
calculate_tax(16, 20000, 'Student')\
**Output:**\
0

===================================

**Example2:** \
**Input:**\
20\
18000\
assistant manager\
**Function Call:**\
calculate_tax(20, 18000, 'assistant manager')\
**Output:**\
900.0


===================================

**Example3:** \
**Input:**\
20\
22000\
assistant manager\
**Function Call:**\
calculate_tax(20, 22000, 'Assistant manager')\
**Output:**\
2200.0

===================================


**Example4:** \
**Input:**\
20\
122000\
president\
**Function Call:**\
calculate_tax(20, 122000, 'president')\
**Output:**\
0

In [ ]:
# to do
def calculate_tax(age, salary,designation):
  tax=0
  if age<18:
    tax=0
  elif designation.lower()=='president':
    tax=0
  elif salary<10000:
    tax=0
  elif salary>10000 and salary<20000:
    tax=salary*(5/100)
  elif salary>20000:
    tax=salary*(10/100)
  return(tax)
age=int(input())
salary=int(input())
designation=input()
print(calculate_tax(age, salary,designation))

22
22000
man
2200.0

### Task 6
Write a function which will take 1 argument, number of days.

Your first task is to take the number of days as user input and pass the value to the function.
 
Your second task is to implement the function and calculate the total number of years, number of months, and the remaining number of days as output. No need to return any value, print inside the function. 

**Note:** Assume, each year to be 365 days and month to be 30 days.

=====================================================

**Hint(1):**  Divide and mod the main input to get the desired output.

**Hint(2):**
This task’s calculation is similar to Assignment-1’s seconds to hours, minutes conversion.

=====================================================

**Example01**

**Input:**\
4330\
**Function Call:**\
function_name(4330)\
**Output:**\
11 years, 10 months and 15 days

================================

**Example02**

**Input:**\
2250\
**Function Call:**\
function_name(2250)\
**Output:**\
6 years, 2 months and 0 days

In [ ]:
# todo
def function_name(day):
  year=day//365
  month= (day%365)//30
  day=(day%365)%30
  print(f'{year} years, {month} months and {day} days')
day=int(input())
function_name(day)

4330
11 years, 10 months and 15 days

### Task 7
Write a function called **show_palindrome** that takes a number as an argument and then returns a palindrome string. Finally, prints the returned value in the function call.

=====================================================

**Example1:** \
**Function Call:**\
show_palindrome(5)\
**Output:**\
123454321

===================

**Example2:** \
**Function Call:**\
show_palindrome(3)\
**Output:**\
12321

In [ ]:
# to do
def show_palindrome(num):
  s=""
  for i in range(1,num+1):
    s=s+str(i)
  for i in range(num-1,0,-1):
    print(i)
    s=s+str(i)
  return(s)
print(show_palindrome(5))

4
3
2
1
123454321

### Task 8
Write a function called **show_palindromic_triangle** that takes a number as an argument and prints a Palindromic Triangle in the function.

**<font color='blue'>[Must reuse the show_palindrome() function of the previous task]</font>**



=====================================================

**Hints(1):** \
Need to use both print() and print( , end = " ") functions


=====================================================

**Example1:** \
**Function Call:**\
show_palindromic_triangle(5)\
**Output:**

&emsp; &emsp; &emsp; &emsp; 1\
&emsp; &emsp; &emsp; 1 &nbsp; 2 &nbsp; 1 \
&emsp; &emsp; 1 &nbsp; 2 &nbsp; 3 &nbsp; 2 &nbsp; 1 \
&emsp; 1 &nbsp; 2 &nbsp; 3 &nbsp; 4 &nbsp; 3 &nbsp; 2 &nbsp; 1 \
1 &nbsp; 2 &nbsp; 3 &nbsp; 4 &nbsp; 5 &nbsp; 4 &nbsp; 3 &nbsp; 2 &nbsp; 1

=============================================================


**Example2:** \
**Function Call:**\
show_palindromic_triangle(3)\
**Output:**

&emsp; &emsp; 1 \
&emsp; 1 &nbsp; 2 &nbsp; 1 \
1 &nbsp; 2 &nbsp; 3 &nbsp; 2 &nbsp; 1

In [ ]:
# to do
def show_palindromic_triangle(n):
  for i in range(0,n):
    for k in range(0,n-i-1):
      print(" ",end=" ")
    for j in range (0,i+1):
      print(j+1,end=" ")
    for t in range(i,0,-1):
      print(t,end=" ")
    print(" ")
show_palindromic_triangle(3)

    1
  1 2 1
1 2 3 2 1

### Task 09
Write a function called **area_circumference_generator** that takes a radius of a circle as a  function parameter and calculates its circumference and area. Then returns these two results as a **tuple** and prints the results using tuple unpacking in the function call accorrding to the given format. 

<font color='blue'>**[Must use tuple packing & unpacking]** </font>

=====================================================

**Example1:** \
**Function Call:**\
area_circumference_generator(1)\
**Output:**\
(3.141592653589793, 6.283185307179586)\
Area of the circle is 3.141592653589793 and circumference is 6.283185307179586

====================================

**Example2:** \
**Function Call:**\
area_circumference_generator(1.5)\
**Output:**\
(7.0685834705770345, 9.42477796076938)\
Area of the circle is 7.0685834705770345 and circumference is 9.42477796076938

====================================


**Example3:** \
**Function Call:**\
area_circumference_generator(2.5)\
**Output:**\
(19.634954084936208, 15.707963267948966)\
Area of the circle is 19.634954084936208 and circumference is 15.707963267948966

In [ ]:
# to do
def area_circumference_generator(radius):
  import math
  area=math.pi*radius*radius
  circumference=2*math.pi*radius
  tup=(area, circumference)                           
  return(tup)
print(area_circumference_generator(2.5))
area,circumference=area_circumference_generator(2.5)
print(f"Area of the circle is {area} and circumference is {circumference} ")

(19.634954084936208, 15.707963267948966)
Area of the circle is 19.634954084936208 and circumference is 15.707963267948966

### Task 10
Write a function called **make_square** that takes a tuple in the parameter as a range of numbers (starting point and ending point (included)). The function should **return a dictionary** with the numbers as keys and its squares as values.

=====================================================

**Hints:** \
You need to declare a dictionary to store the result. You should use the range function to run the “for loop”.


=====================================================

**Example1:** \
**Function Call:**\
make_square((1,3))\
**Output:**\
{1: 1, 2: 4, 3: 9}

====================================

**Example2:** \
**Function Call:**\
make_square((5,9))\
**Output:**\
{5: 25, 6: 36, 7: 49, 8: 64, 9: 81}

In [ ]:
# to do
def make_squre(tup):
  first,last=tup
  dic={}
  for i in range(first,last+1):
    dic[i]=i**2
  return (dic)
print(make_squre((1,3)))

{1: 1, 2: 4, 3: 9}

### Task 11
Write a function called **rem_duplicate** that takes a tuple in the parameter and **return a tuple** removing all the duplicate values. Then print the returned tuple in the function call.

<font color='red'>**[Cannot use remove() or removed() for this task]** </font>

=====================================================

**Hints:** \
Unlike lists, tuples are immutable so, the tuple taken as an argument cannot be modified. But list can be modified and lastly for returning the result use type conversion. You need to use membership operators (in, not in) for preventing adding any duplicates values.

=====================================================


**Example1:** \
**Function Call:**\
rem_duplicate((1,1,1,2,3,4,5,6,6,6,6,4,0,0,0))\
**Output:**\
(1, 2, 3, 4, 5, 6, 0)

====================================

**Example2:** \
**Function Call:**\
rem_duplicate(("Hi", 1, 2, 3, 3, "Hi",'a', 'a', [1,2]))\
**Output:**\
('Hi', 1, 2, 3, 'a', [1, 2])

In [ ]:
# to do
def rem_duplicate(tup):
  l=list(tup)
  l1=[]
  for i in l:
    if i not in l1:
      l1.append(i)
  l1=tuple(l1)
  return(l1)
print(rem_duplicate(("Hi", 1, 2, 3, 3, "Hi",'a', 'a', [1,2])))

('Hi', 1, 2, 3, 'a', [1, 2])

### Task 12
Write a python function that takes a list as an argument. Your task is to create a new list where **each element can be present at max 2 times**. Inside the function, print the number of elements removed from the given list. Finally, return the new list and print the result.

=====================================================

**Hint:** You may use list_name.count(element) to count the total number of times an element is in a list. list_name is your new list for this problem.

=====================================================

**Function Call:**\
function_name([1, 2, 3, 3, 3, 3, 4, 5, 8, 8])\
**Output:**\
Removed: 2\
[1, 2, 3, 3, 4, 5, 8, 8]\
================================\
**Function Call:**\
function_name([10, 10, 15, 15, 20])\
**Output:**\
Removed: 0\
[10, 10, 15, 15, 20]

In [ ]:
# todo
def function_name(l):
  new=[]
  rem=0
  for i in l:
    if new.count(i)<2:
      new.append(i)
    else:
      rem+=1
  print(f"Removed:{rem}")
  print(new)
function_name([1, 2, 3, 3, 3, 3, 4, 5, 8, 8])

[1]
[1, 2]
[1, 2, 3]
[1, 2, 3, 3]
[1, 2, 3, 3, 4]
[1, 2, 3, 3, 4, 5]
[1, 2, 3, 3, 4, 5, 8]
[1, 2, 3, 3, 4, 5, 8, 8]
Removed:2
[1, 2, 3, 3, 4, 5, 8, 8]

### Task 13
Write a python function that will perform the basic calculation (addition, subtraction, multiplication and division) based on 3 arguments. They are:
- Operator ('+', '-', '/', '*')
- First Operand (any number)
- Second Operand (any number)

Your first task is to take these arguments as user input and pass the values to the function parameters.

Your second task is to write a function and performs the calculation based on the given operator. Then, finally return the result in the function call and print the result.

=====================================================

**Input:**\
"+"\
10\
20\
**Function Call:**\
function_name("+", 10, 20)\
**Output:**\
30.0

================================

**Input:**\
"*"\
5.5\
2.5\
**Function Call:**\
function_name("*", 5.5, 2.5)\
**Output:**\
13.75

In [ ]:
def calculate(operator,num1,num2):
  result=0
  if operator=='+':
    result=num1+num2
  elif operator=='-':
    result=num1-num2
  elif operator=='*':
    result=num1*num2
  else:
    result=num1/num2
  return(result)
operator =input()
num1=float(input())
num2=float(input())
print(calculate(operator,num1,num2))

*
5.5
2.5
13.75

### Task 14
Write a function which will take 2 arguments. They are:
- Sentence 
- position 

Your first task is to take these arguments as user input and pass these values to the function parameters.

Your second task is to implement the function and remove the characters at the index number which is divisible by the position (Avoid the index number 0 as it will always be divisible by the position, so no need to remove the index 0 character). 
Finally, add the removed characters at the end of the new string.

Return the value and then finally, print the new string at the function call.

<font color='red'>**[Cannot use remove() or removed() for this task]** </font>

=====================================================

**Input:**\
"I love programming."\
3\
**Function call:**\
function_name("I love programming.", 3)\
**Output:**\
I lveprgrmmngo oai.

==============================================

**Input:**\
"Python is easy to learn. I love python."\
6\
**Function call:**\
function_name("Python is easy to learn. I love python.", 6)\
**Output:**\
Pythonis eay to earn.I lov pythn. sl eo

In [ ]:
#todo
def fun_name(sentence,position):
  st=sentence[0]
  remove=""
  for i in range(1,len(sentence)):
      if i%position!=0:
        st+=sentence[i]
      else:
        remove+=sentence[i]
  return(st+remove)
sentence=input()
position=int(input())
print(fun_name(sentence,position))

I love programming
3
I lveprgrmmngo oai

### Task 15
You have been hired as an app developer for the company. The company plans to make an app for a grocery store where the user can order groceries and see the total amount to be paid in the cart section. 

To build this feature, you have to write a function that takes 2 arguments. They are:
- order_items (must be a list)
- location (default value should be set to "Dhanmondi")

Your first task is to take a list of items from the user. Pass the list into the function parameter along with the optional location (Use default argument technique). (Also, no need to take location as input, pass this any value you want.) 

Your second task is to implement the function. In the function, create a dictionary for the items shown in the table. Calculate the total price of the items passed as a list to the function. Additionally, add a delivery fee of 30 taka if the location is Dhanmondi. Otherwise, add a delivery fee of 70 taka. Finally, return the value and print it.

| Item | Price(Tk) |
| --- | --- |
| Rice | 105 |
| Potato | 20 |
| Chicken | 250 |
| Beef | 510 |
| Oil | 85 |

=====================================================

**Hint:** The keys are the items and values are the corresponding price. Iterate the items in the list and check if the items in the list are available in the dictionary keys or not. If it is available, add the price.

=====================================================

**Example1:**\
function_name(["Rice", "Beef", "Rice"], "Mohakhali")

total = 105 + 510 + 105 = 720 (Take the price of each item and add them.)\
total = 720 + 70 = 790 (Finally, add the delivery fee based on the location.)

**Input:**\
["Rice", "Beef", "Rice"]\
**Function Call:**\
function_name(["Rice", "Beef", "Rice"], "Mohakhali")\
**Output:**\
790

==============================================

**Example2:**

function_name(["Rice", "Beef", "Rice"])

total = 105 + 510 + 105 = 720 (Take the price of each item and add them.)\
total = 720 + 30 = 750 (Since no location is passed in the parameter, it will use the default location-"Dhanmondi". For dhanmondi, delivery fee of 30 taka)

**Input:**\
["Rice", "Beef", "Rice"]\
**Function Call:**\
function_name(["Rice", "Beef", "Rice"])\
**Output:**\
750

In [ ]:
#todo
def grocery(order_items,location='Dhanmondi'):
  total=0
  dic={"Rice":105,"Potato":20,"Chikhen":250,"Beef":510,"Oil":85}
  for i in order_items:
    total=total+dic[i]
  if location=="Dhanmondi":
    total+=30
  else:
    total+=70
  return(total)
order_items=input().split(",")
print(grocery(order_items))

Rice,Beef,Rice
750

## Optional Tasks (16 -21) [Ungraded]

### Task 16
Write a function called **splitting_money** that takes an “amount” of money as a argument.

Your first task is to take the “amount” of money as user input and pass the value to the function paramater.
 
Your second task is to implement the function and calculate how that money can be split into 500, 100, 50, 20, 10, 5, 2, and 1 taka notes.

Then print the returned value in the function call.

=====================================================


**Hints:** \
This task’s calculation is similar to Assignment-1’s seconds to hours, minutes conversion. To return the result containing multiple strings, you need to store it in a variable and return it at the end of the function.

=====================================================


**Example1:** \
If the money is 1234, then the function should return 

"500 Taka: 2 note(s) \
100 Taka: 2 note(s) \
20 Taka: 1 note(s) \
10 Taka: 1 note(s) \
2 Taka: 2 note(s)"

=====================================================

**Example2:** \
If the money is 151, then the function should return

"100 Taka: 1 note(s)\
50 Taka: 1 note(s)\
1 Taka: 1 note(s)"

In [ ]:
#todo
def money(amount):
  notes=[500,100,20,10,2]
  count=[0,0,0,0,0]
  for i,j in zip(notes,count):
    if amount>=i:
      j=amount//i
      amount=amount-j*i
      print(i,":",j)

  
amount=int(input())
money(amount)

151
100 : 1
20 : 2
10 : 1

### Task 17
Write a function called **remove_odd** that takes a list of numbers that have both even and odd numbers mixed. \
Your function should remove all the odd numbers and **return a compact list** which only contains the even numbers. 

<font color='red'>**[Cannot use remove() or removed() for this task]** </font>

=====================================================

**Example1:** \
**Function Call:**\
remove_odd ([21, 33, 44, 66, 11, 1, 88, 45, 10, 9])\
**Output:**\
[44, 66, 88, 10]

====================================

**Example2:** \
**Function Call:**\
remove_odd ([11,2,3,4,5,2,0,5,3])\
**Output:**\
[2, 4, 2, 0]

In [ ]:
#todo
def remove_odd(lst):
  n=[]
  for i in lst:
    if i%2==0:
      n.append(i)
  return(n)
print(remove_odd([11,2,3,4,5,2,0,5,3]))

[2, 4, 2, 0]

In [ ]:
def remove_odd(lst):
  n=[]
  for i in lst:
    if int(i)%2==0:
      n.append(int(i))
  return(n)
lst=input().split(",")
print(remove_odd(lst))

5,5,3,2
[2]

### Task 18
Write a function which will take 4 arguments. They are:
- starting value(inclusive)
- ending value(exclusive)
- first divisor
- second divisor

Your first task is to take these arguments as user input and pass these values to the function.

Your second task is to implement the function and find all the numbers that are divisible by the <u> **first divisor or second divisor but not both**</u> from the starting value(inclusive) and ending value(exclusive). Add all the numbers that are divisible and finally return this value. Print the returned value in the function call.

=====================================================

**Input:**\
10\
40\
4\
7\
**Function Call:**\
function_name(10, 40, 4, 7)\
**Output:**\
210\
================================\
**Input:**\
5\
100\
3\
4\
**Function Call:**\
function_name(5, 100, 3, 4)\
**Output:**\
2012

In [ ]:
#todo
def fun(starting_value,ending_value,first_divisor,second_divisor):
  sum=0
  for i in range(starting_value,ending_value):
    if not(i%first_divisor==0 and i%second_divisor==0):
      if (i%first_divisor==0 or i%second_divisor==0):
        sum+=i
  return(sum)

starting_value= int(input())
ending_value= int(input())
first_divisor= int(input())
second_divisor= int(input())
print(fun(starting_value,ending_value,first_divisor,second_divisor))

5
100
3
4
2012

### Task 19
Write a python function which will take a string as an argument. 

Your first task is to take a string as user input and pass the value to the function.

Your second task is to implement a function which will check whether all the alphabets from a to j (convert all the alphabets to lowercase) has appeared at least once in the given string or not. 
- If all of these alphabets (a to j) appear at least once, then the result will be 5. 
- If any one of the alphabets (a to j) is not in the given string, then the result will be 6.

Return this result and print the statement, "PSG will win the Champions League this season" that many times.

=====================================================

**Example01:**
"A black jackal is hunting a full grown deer" 

Here all the alphabets from A to J are present at least once. So, the function will return 5 and will print the statement 5 times.

**Input:**\
"A black jackal is hunting a full grown deer"\
**Function Call:**\
function_name("A black jackal is hunting a full grown deer")\
**Output:**\
PSG will win the Champions League this season\
PSG will win the Champions League this season\
PSG will win the Champions League this season\
PSG will win the Champions League this season\
PSG will win the Champions League this season

==============================================

**Example02:**

**Input:**\
"ABBCDEFEFGHI"\
**Function Call:**\
function_name("ABBCDEFEFGHI")\
**Output:**\
PSG will win the Champions League this season\
PSG will win the Champions League this season\
PSG will win the Champions League this season\
PSG will win the Champions League this season\
PSG will win the Champions League this season\
PSG will win the Champions League this season

In [ ]:
#todo
def fun(st):
  result=""
  s="abcdefghij"
  for i in s:
    if i in st.lower():
      result=5
    else:
      result=6
      return(result)
  return(result)
  
st=input()                                         #input ekbar print hoy
result=fun(st)
for x in range (result):
   print(x)
   print("PSG will win the Champions League this season")

PSG will win the Champions League this season
0
PSG will win the Champions League this season
1
PSG will win the Champions League this season
2
PSG will win the Champions League this season
3
PSG will win the Champions League this season
4
PSG will win the Champions League this season
5
PSG will win the Champions League this season

### Task 20
Write a function called **individul_bonus_calculation** which will take 4 arguments. They are:

- The player name
- Yearly earning of that player
- The total goal scored this season by that player
- Bonus percent per goal.


Your task is to implement the above-mentioned function that will calculate the total bonus on the yearly earnings of a player for the total goals he had scored.

Additionally, 
 * If the goal scored is above 30, add a (additional) bonus of 10000 taka.
 * If it is between 20 and 30 inclusive, add an extra 5000 taka.

<font color='blue'>[ For this task, no need to take any input from the user. Call the functions and print the values inside the function. ] </font>



=====================================================

**Example1:**\
individul_bonus_calculation("Neymar", 1200000, 35, 5)

bonus = 35 * (5 / 100 * 1200000) + 10000 = 2110000

**Function call:**\
individul_bonus_calculation("Neymar", 1200000, 35, 5)\
**Output:**\
Neymar earned a bonus of  2110000 Taka for 35 goals.

=====================================================

**Example2:**\
individul_bonus_calculation('Jamal', 700000, 19, 8)

bonus = 19 * (8 / 100 * 700000) + 0 = 1064000

**Function call:**\
individul_bonus_calculation('Jamal', 700000, 19, 8)\
**Output:**\
Jamal earned a bonus of 1064000 Taka for 19 goals.

=====================================================

**Example3:**\
individul_bonus_calculation('Luis', 80000, 25, 10)

bonus = 25 * (10 / 100 * 80000) + 5000 = 205000

**Function call:**\
individul_bonus_calculation('Luis', 80000, 25, 10)\
**Output:**\
Luis earned a bonus of 205000 Taka for 25 goals.

=====================================================

In [ ]:
def f(name,earn,goal,bonus):
  if goal>30:
    pos=10000
  elif goal>20 or goal<=30:
    pos=5000
  total = goal * (bonus/ 100 * earn) + pos
  print(f"{name} earned a bonus of {total} Taka for {goal}")
f('Luis', 80000, 25, 10)

Luis earned a bonus of 205000.0 Taka for 25

1. Write a function in Python that will take a string text as input from the user and returns the list of
unique characters concatenated with their ASCII value at the front and back side.

==================================================
Sample Input:

"pythonbook"


Function Calling:

function_name("pythonbook")


Sample Output:

['112p112', '121y121', '116t116', '104h104', '111o111', '110n110', '98b98', '107k107']

In [ ]:
def f (s):
  l=[]
  for i in s:
    m=str(ord(i))+i+str(ord(i))
    if m not in l:
      l.append(m)
  return(l)

s=input()
print(f(s))

pythonbook
['112p112', '121y121', '116t116', '104h104', '111o111', '110n110', '98b98', '107k107']

2. Write a function in Python that will take a string text as input from the user and returns a dictionary
having the unique characters as the keys and the list of their both-way indexes (positive and negative
index) as the values.

==================================================

Sample Input:

"pythonbook"

Function Calling:

function_name("pythonbook")

Sample Output:

{'p': [0, -10], 'y': [1, -9], 't': [2, -8], 'h': [3, -7], 'o': [4, -6, 7, -3, 8, -2], 'n': [5, -5], 'b': [6, -4], 'k':
[9, -1]}

In [ ]:
def func_index(str_1):
  dict_1={}
  for i in str_1:
    dict_1[i]=[]
  for i in range(0,len(str_1)):
    dict_1[str_1[i]].append(i)
    dict_1[str_1[i]].append((len(str_1)-i)*(-1))
  print(dict_1)
func_index("pythonbook")

{'p': [0, -10], 'y': [1, -9], 't': [2, -8], 'h': [3, -7], 'o': [4, -6, 7, -3, 8, -2], 'n': [5, -5], 'b': [6, -4], 'k': [9, -1]}

3. Write a function in Python that will take a space separated string text as input from the user and
returns a dictionary having the unique words as the keys and their frequency in the given text as the
values in a sorted order(ascending) according to the frequencies.

==================================================

Hints (1):

Frequencies of the words can be easily counted with built-in function count().

Hints (2):

Sorting according to frequencies can be done in two approaches.

Approach (1): Use the built-in sorted() function. Here, for the key, you need to call a custom-made
function that will return frequencies for each word. So, the sorted() function will return values sorted
according to the frequencies.

Approach (2): Make two lists. One with the keys and other one with the frequencies. For a particular
keys, values should be found in the same index of the frequencies list. Then similar to the
Assignment07 Task-5. Sort the values of frequencies and in time of swapping, swap BOTH keys &
frequencies. You can use any one of the sorting algorithms taught (Bubble sort or Selection sort)

==================================================

Sample Input1:

"go there come and go here and there go care"


Function Call1:

function_name("go there come and go here and there go care")


Sample Output1:

{'come': 1, 'here': 1, 'care': 1, 'there': 2, 'and': 2, 'go': 3}

In [7]:
def f(s):
  
  l=[str(l) for l in s.split(" ")]
  dic={}
  for j in l:
    a=l.count(j)
    dic[j]=a                                             
  print(dic)

f('go there come and go here and there go care')

{'go': 3, 'there': 2, 'come': 1, 'and': 2, 'here': 1, 'care': 1}

4. Write a function in Python that will take a number string text as input from the user and returns a
dictionary having the unique numbers as the keys and the tuple of being the number to be even, odd,
prime and perfect as thevalues.

==================================================

Hints (1): Write a function to check whether a number is Perfect or not and RETURN “Perfect” and “Not

Perfect” accordingly.
Hints 
(2): Write a function to check whether a number is Prime or not and RETURN “Prime” and “NotPrime” accordingly.

Hints (3): Write a function to check whether a number is Even or not and RETURN “Even” and “Odd”accordingly.

Hints (4): Call 3 above mentioned functions and store their returned values in a list/tuple.

even= even_check()

prime= prime_check()

perfect= perfect_check()

tup_for_digit = (even, prime, perfect)

==================================================
Sample Input1:

"2441396"

Function Call1:

function_name("2441396")

Sample Output1:

{2: ('even', 'prime', 'not perfect'), 4: ('even', 'not prime', 'not perfect'), 1: ('odd', 'not
prime', 'not perfect'), 3: ('odd', 'prime', 'not perfect'), 9: ('odd', 'not prime', 'not perfect'), 6: ('even', 'not
prime', 'perfect')}

In [ ]:
def even_check(num):
  if num%2==0:
    result= "even"
  else:
    result= "odd"
  return result
def perfect_check(num):
  sum_num=0
  for i in range(1,num):
    if num%i==0:
      sum_num+=i
  if sum_num==num:
    result= "perfect"
  else:
    result= "not perfect"
  return result
def prime_check(num):
  count=0
  for i in range(1,num):
    if num%i==0:
      count+=1
  if count==1:
    result= "prime"
  else:
    result= "not prime"
  return result
def func(str_num):
  dict_num={}
  for i in str_num:
    even= even_check(int(i))
    prime= prime_check(int(i))
    perfect= perfect_check(int(i))
    dict_num[int(i)]=(even, prime, perfect)
  return dict_num
num= input("Enter numbers: ")
print(func(num))

Enter numbers: 224455678
{2: ('even', 'prime', 'not perfect'), 4: ('even', 'not prime', 'not perfect'), 5: ('odd', 'prime', 'not perfect'), 6: ('even', 'not prime', 'perfect'), 7: ('odd', 'prime', 'not perfect'), 8: ('even', 'not prime', 'not perfect')}

5. Assume, you have been given two matrixes in list format. Write a function in Python that will
calculate the summation of these two matrices. Then RETURN the summation matrix and print it in the
function call. [A matrix can only be added to another matrix if the two matrices have the same
dimension] [Avoid using built-in Functions]

===================================================================

Given Matrix1:

matrix_A = [ [1,5], [-4,3]]

matrix_B = [ [2,-1] , [4,-1] ]

Function Call1:

function_name(matrix_A , matrix_B)

Sample Output1:

matrix_sum = [ [3,4] , [0,2] ]

Explanation1:

Inside matrix_A and matrix_B, each list is a row matrix.

For example, In matrix_A, Row 1 ----> [1, 5]
Row 2----> [4, 3]


In matrix_B, Row 1 ----> [2, -1]
Row 2----> [4, -1]

So, in output, matrix_sum = [ [1+2 , 5 -1]
[-4+ 4, 4 -1] ]

===================================================================

Given Matrix2:

matrix_A = [ [1,5, 4] , [-4,3, 3] ]

matrix_B = [ [2,-1, -3] , [4,-1, -4] ]

Function Call2:

function_name(matrix_A , matrix_B)

Sample Output2:

matrix_sum = [[3, 4, 1], [0, 2, -1]]

===================================================================

Given Matrix3:

matrix_A = [ [1,5, 4] , [-4,3, 3] ,[-4,0, 6]]

matrix_B = [ [2,-1, -3] , [4,-1, -4], [2,6, 3] ]

Function Call3:

function_name(matrix_A , matrix_B)

Sample Output3:

matrix_sum = [[3, 4, 1], [0, 2, -1], [-2, 6, 9]]


Page 5 of 9

===================================================================

Given Matrix4:

matrix_A = [ [1,5] , [-4,3], [9,2]]

matrix_B = [ [ [2,-1] , [4,-1] ]] ]

Function Call4:

function_name(matrix_A , matrix_B)

Sample Output4:

No of rows not same

===================================================================

Given Matrix5:

matrix_A = [ [1,5, 4] , [-4,3] ,[-4,0, 6]]

matrix_B = [ [2,-1, -3] , [4,-1, -4], [2,6] ]

Function Call5:

function_name(matrix_A , matrix_B)

Sample Output5:

No of columns not same

===================================================================

In [ ]:
def matrix(matrix1, matrix2):
    result= True
    sum_li=[]
    if len(matrix1)==len(matrix2):
        for i in range(0,len(matrix1)):
            li_row=[]
            if len(matrix1[i])==len(matrix2[i]):
                for j in range(0,len(matrix1[i])):
                    sum= matrix1[i][j]+matrix2[i][j]
                    li_row.append(sum)
                sum_li.append(li_row)
            else:
                print("No of columns not same")
                result= False
                break
    else:
        print("No of rows not same")
        result= False
    if result== True:
          return sum_li
matrix1= [ [1,5], [-4,3]]
matrix2= [ [2,-1] , [4,-1] ]
out= matrix(matrix1, matrix2)
if out!= None:
  print("Matrix sum:",out)

Matrix sum: [[3, 4], [0, 2]]

6. Assume, you have been given a Matrix in a list format. Write a Python function called
print_matrix_list() that will take a list as an argument and print the Matrix in its proper square form.


===================================================================

Given Matrix1:

matrix= [[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 3], [9, 1, 2, 3]]

Function Call1:

print_matrix_list(matrix)

Sample Output1:

1 2 3 4

4 5 6 7

7 8 9 3

9 1 2 3

===================================================================

Given Matrix2:

matrix= [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Function Call2:

print_matrix_list(matrix)

Sample Output2:

1 2 3

4 5 6

7 8 9

===================================================================

Given Matrix3:

matrix= [[1, 0, 0, 0], [0, 5, 0, 0], [0, 0, 9, 0], [0, 0, 0, 3]]

Function Call3:

print_matrix_list(matrix)

Sample Output3:

1 0 0 0

0 5 0 0

0 0 9 0

0 0 0 3

===================================================================

In [ ]:
def print_matrix_list(matrix):
  for i in matrix:
    for j in i:
      print(str(j), end=" ")
    print()
matrix=[[1, 0, 0, 0], [0, 5, 0, 0], [0, 0, 9, 0], [0, 0, 0, 3]]
print_matrix_list(matrix)

1 0 0 0
0 5 0 0
0 0 9 0
0 0 0 3

Assume, you have been given a Square Matrix in a dictionary format.
Square Matrix: A square matrix is a matrix with the same number of rows and columns.

Now, write function called convert_to_list(), which converts the dictionary into a list of lists and returns

the list where each list represents a row matrix. Then, print the returned list in the function call. Finally,
print the returned matrix in Square format using the print_matrix_list() function.

===================================================================

Given1:

square_matrix_dict = {1 : [1,2,3,4] , 2 : [4,5,6,7] , 3 : [7,8,9,3] , 4:[9,1,2,3] }

Function Call1:

convert_to_list(square_matrix_dict)

Sample Output1:

[[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 3], [9, 1, 2, 3]]

===================================================================

Given2:

square_matrix_dict = {1 : [1,2,3] , 2 : [4,5,6] , 3 : [7,8,9] }

Function Call2:

convert_to_list(square_matrix_dict)

Sample Output2:

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

===================================================================

In [ ]:
def print_matrix_list(matrix):
  for i in matrix:
    for j in i:
      print(str(j), end=" ")
    print()
def convert_to_list(dict_matrix):
  matrix_list=[]
  for i in dict_matrix.keys():
    matrix_list.append(dict_matrix[i])
  return matrix_list
dict_matrix= {1 : [1,2,3,4] , 2 : [4,5,6,7] , 3 : [7,8,9,3] , 4:[9,1,2,3] }
list_matrix= convert_to_list(dict_matrix)
print("Matrix in list format:",list_matrix)
print("=============================\n**Matrix in square format**")
print_matrix_list(list_matrix)

Matrix in list format: [[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 3], [9, 1, 2, 3]]
=============================
**Matrix in square format**
1 2 3 4
4 5 6 7
7 8 9 3
9 1 2 3

8. Assume, you have been given a Square Matrix in a dictionary format. Now, write function called
convert_to_diagonal() which converts the Square Matrix into a Diagonal Matrix. Then prints both the
Square Matrix and Diagonal Matrix in list of list format and their original square format.

[ For printing in square format MUST use the print_matrix_list() function.]

Square Matrix: A square matrix is a matrix with the same number of rows and columns.

Diagonal Matrix: Any given square matrix where all the elements are zero except for the elements that
are present diagonally is called a diagonal matrix.


===================================================================

Hints:

Step1: Inside the convert_to_diagonal(), call convert_to_list() for converting the dictionary into a list
of lists.

Step2: Store and print the returned Square- Non-diagonal matrix in a variable.

Step3: Call the print_matrix_list() with the returned Square- Non-diagonal matrix for printing it in the
original square format.

Step4: Except for the cases, when row_number & column_no is equal, make all other elements 0. By
doing this, you will get your Diagonal matrix.
Step5: Call the print_matrix_list() with the Diagonal matrix made in step4 matrix for printing it in the
original square format.

===================================================================

Given1:

square_matrix_dict = {1 : [1,2,3,4] , 2 : [4,5,6,7] , 3 : [7,8,9,3] , 4:[9,1,2,3] }

Function Call1:

convert_to_diagonal(square_matrix_dict)

Sample Output1:

Non-diagonal matrix:

In list of list format: [[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 3], [9, 1, 2, 3]]
in original square format:

1 2 3 4

4 5 6 7

7 8 9 3

9 1 2 3

================

Diagonal matrix:

In list of list format: [[1, 0, 0, 0], [0, 5, 0, 0], [0, 0, 9, 0], [0, 0, 0, 3]]
in original square format:

1 0 0 0

0 5 0 0

0 0 9 0

0 0 0 3

Given2:

square_matrix_dict = {1 : [1,2,3] , 2 : [4,5,6] , 3 : [7,8,9] }

Function Call2:

convert_to_diagonal(square_matrix_dict)

Sample Output2:

Non-Diagonal matrix:

In list of list format: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

in original square format:

1 2 3

4 5 6

7 8 9

================

Diagonal matrix:

In list of list format: [[1, 0, 0], [0, 5, 0], [0, 0, 9]]

in original square format:

1 0 0

0 5 0

0 0 9

In [ ]:
def print_matrix_list(matrix):
  for i in matrix:
    for j in i:
      print(str(j), end=" ")
    print()
def convert_to_list(dict_matrix):
  matrix_list=[]
  for i in dict_matrix.keys():
    matrix_list.append(dict_matrix[i])
  return matrix_list
def convert_to_diagonal(matrix_list):
  for i in range(0,len(matrix_list)):
    for j in range(0,len(matrix_list[i])):
      if i!=j:
        matrix_list[i][j]=0
  print("In list of list format:",matrix_list)
  print("In original square format:")
  print_matrix_list(matrix_list)
dict_matrix= {1 : [1,2,3,4] , 2 : [4,5,6,7] , 3 : [7,8,9,3] , 4:[9,1,2,3] }
list_matrix= convert_to_list(dict_matrix)
print("\nNon-Diagonal matrix:")
print("In list of list format:",list_matrix)
print("In original square format:")
print_matrix_list(list_matrix)
print("\nDiagonal matrix:")
convert_to_diagonal(list_matrix)

Non-Diagonal matrix:
In list of list format: [[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 3], [9, 1, 2, 3]]
In original square format:
1 2 3 4
4 5 6 7
7 8 9 3
9 1 2 3

Diagonal matrix:
In list of list format: [[1, 0, 0, 0], [0, 5, 0, 0], [0, 0, 9, 0], [0, 0, 0, 3]]
In original square format:
1 0 0 0
0 5 0 0
0 0 9 0
0 0 0 3